// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

// -------------------
// Customized enums
// -------------------

namespace BehavicTree
{
	public enum TStandType
	{
		S = 0,
		C = 1,
		A = 2,
		L = 3,
	}
}

namespace BehavicTree
{
	public enum TPhysicType
	{
		S = 0,
		C = 1,
		A = 2,
	}
}

namespace BehavicTree
{
	public enum TMoveType
	{
		None = 0,
		A = 1,
		I = 2,
		H = 3,
	}
}

// -------------------
// Customized structs
// -------------------

namespace BehavicTree
{
	public struct Vec2
	{
		public float x;
		public float y;
	}
}
