// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT
using UnityEngine;
///<<< END WRITING YOUR CODE

namespace BehavicTree
{
///<<< BEGIN WRITING YOUR CODE NAMESPACE_INIT
[RequireComponent(typeof(CnsCommander))]
///<<< END WRITING YOUR CODE

	public class FightAgent
///<<< BEGIN WRITING YOUR CODE FightAgent
///<<< END WRITING YOUR CODE
	{
		private BehavicTree.TMoveType movetype = BehavicTree.TMoveType.None;
		public void _set_movetype(BehavicTree.TMoveType value)
		{
			movetype = value;
		}
		public BehavicTree.TMoveType _get_movetype()
		{
			return movetype;
		}

		private BehavicTree.TPhysicType physics = BehavicTree.TPhysicType.S;
		public void _set_physics(BehavicTree.TPhysicType value)
		{
			physics = value;
		}
		public BehavicTree.TPhysicType _get_physics()
		{
			return physics;
		}

		private BehavicTree.TStandType type = BehavicTree.TStandType.S;
		public void _set_type(BehavicTree.TStandType value)
		{
			type = value;
		}
		public BehavicTree.TStandType _get_type()
		{
			return type;
		}

		public float ACos(float v)
		{
///<<< BEGIN WRITING YOUR CODE ACos
			return this.Cns.ACos(v);
///<<< END WRITING YOUR CODE
		}

		public void AngleAdd(float angle)
		{
///<<< BEGIN WRITING YOUR CODE AngleAdd
			this.Cns.AngleAdd(angle);
///<<< END WRITING YOUR CODE
		}

		public void AngleSet(float angle)
		{
///<<< BEGIN WRITING YOUR CODE AngleSet
			this.AngleSet(angle);
///<<< END WRITING YOUR CODE
		}

		public int AnimElem()
		{
///<<< BEGIN WRITING YOUR CODE AnimElem
			return this.Cns.AnimElem();
///<<< END WRITING YOUR CODE
		}

		public int AnimElemTime(int lookFrame)
		{
///<<< BEGIN WRITING YOUR CODE AnimElemTime
			return this.Cns.AnimElemTime(lookFrame);
///<<< END WRITING YOUR CODE
		}

		public bool AnimExist(int actionNo)
		{
///<<< BEGIN WRITING YOUR CODE AnimExist
			return this.Cns.AnimExist(actionNo);
///<<< END WRITING YOUR CODE
		}

		public int AnimNO()
		{
///<<< BEGIN WRITING YOUR CODE AnimNO
			return this.Cns.AnimNO();
///<<< END WRITING YOUR CODE
		}

		public int AnimTime()
		{
///<<< BEGIN WRITING YOUR CODE AnimTime
			return this.Cns.AnimTime();
///<<< END WRITING YOUR CODE
		}

		public float Asin(float v)
		{
///<<< BEGIN WRITING YOUR CODE Asin
			return this.Cns.Asin(v);
///<<< END WRITING YOUR CODE
		}

		public float Atan(float v)
		{
///<<< BEGIN WRITING YOUR CODE Atan
			return this.Cns.Atan(v);
///<<< END WRITING YOUR CODE
		}

		public bool CanCtrl()
		{
///<<< BEGIN WRITING YOUR CODE CanCtrl
			return this.Cns.CanCtrl();
///<<< END WRITING YOUR CODE
		}

		public int Ceil(float v)
		{
///<<< BEGIN WRITING YOUR CODE Ceil
			return this.Cns.Ceil(v);
///<<< END WRITING YOUR CODE
		}

		public void ChangeAnim(int animNo, bool isLoop)
		{
///<<< BEGIN WRITING YOUR CODE ChangeAnim
			this.Cns.ChangeAnim(animNo, isLoop);
///<<< END WRITING YOUR CODE
		}

		public void ChangeState(int stateNo)
		{
///<<< BEGIN WRITING YOUR CODE ChangeState
			this.ChangeState(stateNo);
///<<< END WRITING YOUR CODE
		}

		public float Cos(float a)
		{
///<<< BEGIN WRITING YOUR CODE Cos
			return this.Cns.Cos(a);
///<<< END WRITING YOUR CODE
		}

		public void Ctrl(int v)
		{
///<<< BEGIN WRITING YOUR CODE Ctrl
			this.Cns.Ctrl(v);
///<<< END WRITING YOUR CODE
		}

		public void CtrlSet(int v)
		{
///<<< BEGIN WRITING YOUR CODE CtrlSet
			this.Cns.CtrlSet(v);
///<<< END WRITING YOUR CODE
		}

		public void DestroySelf()
		{
///<<< BEGIN WRITING YOUR CODE DestroySelf
			this.Cns.DestroySelf();
///<<< END WRITING YOUR CODE
		}

		public float Exp(float v)
		{
///<<< BEGIN WRITING YOUR CODE Exp
			return this.Cns.Exp(v);
///<<< END WRITING YOUR CODE
		}

		public float fAbs(float value)
		{
///<<< BEGIN WRITING YOUR CODE fAbs
			return this.Cns.Abs(value);
///<<< END WRITING YOUR CODE
		}

		public int Facing()
		{
///<<< BEGIN WRITING YOUR CODE Facing
			return this.Cns.Facing();
///<<< END WRITING YOUR CODE
		}

		public int Floor(float v)
		{
///<<< BEGIN WRITING YOUR CODE Floor
			return this.Cns.Floor(v);
///<<< END WRITING YOUR CODE
		}

		public float fVal(int idx)
		{
///<<< BEGIN WRITING YOUR CODE fVal
			return this.Cns.fVal(idx);
///<<< END WRITING YOUR CODE
		}

		public void fVarAdd(int idx, float add)
		{
///<<< BEGIN WRITING YOUR CODE fVarAdd
			this.Cns.VarAdd(idx, add);
///<<< END WRITING YOUR CODE
		}

		public void fVarSet(int idx, float value)
		{
///<<< BEGIN WRITING YOUR CODE fVarSet
			this.Cns.VarSet(idx, value);
///<<< END WRITING YOUR CODE
		}

		public int iAbs(int value)
		{
///<<< BEGIN WRITING YOUR CODE iAbs
			return this.Cns.Abs(value);
///<<< END WRITING YOUR CODE
		}

		public bool IsAlive()
		{
///<<< BEGIN WRITING YOUR CODE IsAlive
			return this.Cns.IsAlive();
///<<< END WRITING YOUR CODE
		}

		public int iVal(int idx)
		{
///<<< BEGIN WRITING YOUR CODE iVal
			return this.Cns.iVal(idx);
///<<< END WRITING YOUR CODE
		}

		public void iVarAdd(int idx, int add)
		{
///<<< BEGIN WRITING YOUR CODE iVarAdd
			this.Cns.VarAdd(idx, add);
///<<< END WRITING YOUR CODE
		}

		public void iVarSet(int idx, int value)
		{
///<<< BEGIN WRITING YOUR CODE iVarSet
			this.Cns.VarSet(idx, value);
///<<< END WRITING YOUR CODE
		}

		public int Life()
		{
///<<< BEGIN WRITING YOUR CODE Life
			return this.Cns.Life();
///<<< END WRITING YOUR CODE
		}

		public float Log(float exp1, float exp2)
		{
///<<< BEGIN WRITING YOUR CODE Log
			return this.Cns.Log(exp1, exp2);
///<<< END WRITING YOUR CODE
		}

		public float Pi()
		{
///<<< BEGIN WRITING YOUR CODE Pi
			return this.Cns.Pi();
///<<< END WRITING YOUR CODE
		}

		public void PlaySnd(int group, int image)
		{
///<<< BEGIN WRITING YOUR CODE PlaySnd
			this.Cns.PlaySnd(group, image);
///<<< END WRITING YOUR CODE
		}

		public int PrevStateNo()
		{
///<<< BEGIN WRITING YOUR CODE PrevStateNo
			return this.Cns.PrevStateNo();
///<<< END WRITING YOUR CODE
		}

		public int Random()
		{
///<<< BEGIN WRITING YOUR CODE Random
			return this.Cns.Random();
///<<< END WRITING YOUR CODE
		}

		public float Sin(float angle)
		{
///<<< BEGIN WRITING YOUR CODE Sin
			return this.Cns.Sin(angle);
///<<< END WRITING YOUR CODE
		}

		public int StateNo()
		{
///<<< BEGIN WRITING YOUR CODE StateNo
			return this.Cns.StateNo();
///<<< END WRITING YOUR CODE
		}

		public BehavicTree.TStandType StateType()
		{
///<<< BEGIN WRITING YOUR CODE StateType
			return this.type;
///<<< END WRITING YOUR CODE
		}

		public float SysFVar(int idx)
		{
///<<< BEGIN WRITING YOUR CODE SysFVar
			return this.Cns.SysFVar(idx);
///<<< END WRITING YOUR CODE
		}

		public int SysVar(int idx)
		{
///<<< BEGIN WRITING YOUR CODE SysVar
			return this.Cns.SysVar(idx);
///<<< END WRITING YOUR CODE
		}

		public int Time()
		{
///<<< BEGIN WRITING YOUR CODE Time
			return this.Cns.Time();
///<<< END WRITING YOUR CODE
		}

		public bool TimeMod(int divFrame, int modValue)
		{
///<<< BEGIN WRITING YOUR CODE TimeMod
			return this.Cns.TimeMod(divFrame, modValue);
///<<< END WRITING YOUR CODE
		}

		public void VarRandom(int idx, int range)
		{
///<<< BEGIN WRITING YOUR CODE VarRandom
			this.Cns.VarRandom(idx, range);
///<<< END WRITING YOUR CODE
		}

		public BehavicTree.Vec2 Vec()
		{
			///<<< BEGIN WRITING YOUR CODE Vec
			Vec2 ret;
			ret.x = this.Cns.Vec().x;
			ret.y = this.Cns.Vec().y;
			return ret;
///<<< END WRITING YOUR CODE
		}

		public float VecX()
		{
///<<< BEGIN WRITING YOUR CODE VecX
			return this.Cns.VecX();
///<<< END WRITING YOUR CODE
		}

		public float VecY()
		{
///<<< BEGIN WRITING YOUR CODE VecY
			return this.Cns.VecY();
///<<< END WRITING YOUR CODE
		}

		public void velset(float x, float y)
		{
///<<< BEGIN WRITING YOUR CODE velset
			this.Mover.Vec.x = x;
			this.Mover.Vec.y = y;
///<<< END WRITING YOUR CODE
		}

		public void xScaleSet(float scale)
		{
///<<< BEGIN WRITING YOUR CODE xScaleSet
			this.Cns.xScaleSet(scale);
///<<< END WRITING YOUR CODE
		}

		public void yScaleSet(float scale)
		{
///<<< BEGIN WRITING YOUR CODE yScaleSet
			this.Cns.yScaleSet(scale);
			///<<< END WRITING YOUR CODE
		}

///<<< BEGIN WRITING YOUR CODE CLASS_PART

		protected CnsCommander Cns {
			get {
				if (m_Cns == null)
					m_Cns = GetComponent<CnsCommander>();
				return m_Cns;
			}
        }

		protected Movement Mover {
			get {
				if (m_Mover == null)
					m_Mover = GetComponent<Movement>();
				return m_Mover;
			}
		}

		private CnsCommander m_Cns = null;
		private Movement m_Mover = null;
///<<< END WRITING YOUR CODE

	}

///<<< BEGIN WRITING YOUR CODE NAMESPACE_UNINIT

	///<<< END WRITING YOUR CODE
}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

